apiVersion: apps/v1
kind: Deployment
metadata:
  name: obljubadeladolg-deployment
  labels:
    app: obljubadeladolg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obljubadeladolg
  template:
    metadata:
      labels:
        app: obljubadeladolg
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
        - name: obljubadeladolg-storage
          emptyDir: {}
      initContainers:
        - name: collectstatic
          image: obljubadeladolg
          volumeMounts:
            - name: obljubadeladolg-storage
              mountPath: /vc
          command:
            - python
            - manage.py
            - collectstatic
            - --no-input
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: obljubadeladolg.settings.production
          envFrom:
            - secretRef:
                name: obljubadeladolg-credentials
          resources:
            requests:
              memory: 200Mi
              cpu: 100m
            limits:
              memory: 200Mi
              cpu: 100m
        - name: migrate
          image: obljubadeladolg
          command:
            - python
            - manage.py
            - migrate
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: obljubadeladolg.settings.production
          envFrom:
            - secretRef:
                name: obljubadeladolg-credentials
          resources:
            requests:
              memory: 200Mi
              cpu: 100m
            limits:
              memory: 200Mi
              cpu: 100m
      containers:
        - name: obljubadeladolg
          image: obljubadeladolg
          volumeMounts:
            - name: obljubadeladolg-storage
              mountPath: /vc
          command:
            - gunicorn
            - obljubadeladolg.wsgi:application
            - -b
            - 0.0.0.0:8000
            - --log-level
            - DEBUG
          ports:
            - containerPort: 8000
          envFrom:
              - secretRef:
                  name: obljubadeladolg-credentials
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: obljubadeladolg.settings.production
            # - name: DJANGO_DEBUG
            #   value: 'True'
          resources:
            requests:
              memory: 200Mi
              cpu: 1000m
            limits:
              memory: 200Mi
              cpu: 1000m
        - name: obljubadeladolg-nginx
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          image: nginx:alpine
          volumeMounts:
            - name: obljubadeladolg-storage
              mountPath: /usr/share/nginx/html
          resources:
            requests:
              memory: 100Mi
              cpu: 50m
            limits:
              memory: 100Mi
              cpu: 50m
