apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: obljubadeladolg
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: obljubadeladolg
    newName: rg.fr-par.scw.cloud/djnd/obljubadeladolg
    newTag: '329c1844c7a1383965738262ee56a4ef0d5a83a2'
