apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: obljubadeladolg
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: obljubadeladolg
    newName: rg.fr-par.scw.cloud/djnd/obljubadeladolg
    newTag: 'e5a91f9f499554ae33952379e77742261cf2cd99'
