apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: obljubadeladolg
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: obljubadeladolg
    newName: rg.fr-par.scw.cloud/djnd/obljubadeladolg
    newTag: '93f5bb5ffa9e1c63df6c92c7182c1c3b5359f1c2'
