apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: obljubadeladolg
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml
images:
  - name: obljubadeladolg
    newName: rg.fr-par.scw.cloud/djnd/obljubadeladolg
    newTag: '48fed7f5cb79787a85c51b0f2d990c22fe23c228'
