apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: obljubadeladolg-staging
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml
images:
  - name: obljubadeladolg-staging
    newName: rg.fr-par.scw.cloud/djnd/obljubadeladolg-staging
    newTag: '6eb28d0f4c2285e85cdda6f96f46a7966fd67ff4'
