apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: obljubadeladolg
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: obljubadeladolg
    newName: rg.fr-par.scw.cloud/djnd/obljubadeladolg
    newTag: 'f1ccfcfff0f224921e7a88ca31b889df5bb0b328'
