apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: obljubadeladolg-staging
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml
images:
  - name: obljubadeladolg-staging
    newName: rg.fr-par.scw.cloud/djnd/obljubadeladolg-staging
    newTag: 'cef12ad8dad05f40ca748d21c078604c60a9962a'
