apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obljubadeladolg-pvc
  labels:
    app: obljubadeladolg
  annotations:
    pv.beta.kubernetes.io/gid: "1000"
spec:
  storageClassName: 'scw-bssd-retain'
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
