apiVersion: v1
kind: Service
metadata:
  name: obljubadeladolg
spec:
  selector:
    app: obljubadeladolg
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: obljubadeladolg-nginx
spec:
  selector:
    app: obljubadeladolg
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
