# Generated by Django 3.2.3 on 2021-06-03 14:17

from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('home', '0004_promisecategory_promisestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('body', wagtail.core.fields.StreamField([('rich_text', wagtail.core.blocks.StructBlock([('alignment', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Leva'), ('center', 'Sredinska'), ('right', 'Desna')], label='Poravnava')), ('aligned_content', wagtail.core.blocks.StreamBlock([('text', wagtail.core.blocks.RichTextBlock(label='Obogateno besedilo')), ('table', wagtail.contrib.table_block.blocks.TableBlock(label='Tabela', template='home/blocks/table.html'))], label='Vsebina'))]))], blank=True, null=True, verbose_name='Vsebina')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
