# Generated by Django 3.2.3 on 2021-06-03 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('home', '0006_auto_20210603_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromiseListingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('search_title', models.CharField(blank=True, max_length=255, null=True)),
                ('category_label', models.CharField(blank=True, max_length=255, null=True)),
                ('category_placeholder', models.CharField(blank=True, max_length=255, null=True)),
                ('search_label', models.CharField(blank=True, max_length=255, null=True)),
                ('search_placeholder', models.CharField(blank=True, max_length=255, null=True)),
                ('status_help_label', models.CharField(blank=True, max_length=255, null=True)),
                ('status_help_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
