# Generated by Django 3.2.3 on 2021-06-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210604_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='promisepage',
            name='full_text',
            field=models.TextField(blank=True, null=True, verbose_name='Polno besedilo obljube'),
        ),
    ]
