# Generated by Django 3.2.3 on 2021-06-04 10:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_promisepage_full_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promisestatus',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Opis'),
        ),
        migrations.CreateModel(
            name='PromiseUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Naslov')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Datum')),
                ('content', wagtail.core.fields.RichTextField(verbose_name='Vsebina')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='home.promisepage')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.promisestatus', verbose_name='Stanje')),
            ],
        ),
    ]
