# Generated by Django 3.2.3 on 2021-06-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210604_1223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promiseupdate',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='promiseupdate',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
