# Generated by Django 3.2.4 on 2021-06-07 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0012_auto_20210604_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Slika'),
        ),
        migrations.AlterField(
            model_name='promiselistingpage',
            name='search_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Naslov te strani, ko prikazuje rezultate iskanja'),
        ),
    ]
