# Generated by Django 3.2.4 on 2021-06-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210607_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='more_link_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
