# Generated by Django 3.2.4 on 2021-06-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_homepage_more_link_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='metasettings',
            name='newsletter_sublabel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
