# Generated by Django 3.2.4 on 2021-06-09 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0023_add_choose_permissions"),
        ("home", "0016_promisecategory_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="promisestatus",
            name="icon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Ikona",
            ),
        ),
    ]
