# Generated by Django 3.2.4 on 2021-06-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_promisestatus_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='latest_button_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
