# Generated by Django 3.2.4 on 2021-06-10 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0018_homepage_latest_button_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='newsletter_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Slika ob polju za prijavo na novice'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='social_media_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Slika ob polju za delitev na družbenih omrežjih'),
        ),
    ]
