# Generated by Django 3.2.4 on 2021-06-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_metasettings_share_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='promisepage',
            name='quote',
            field=models.TextField(blank=True, null=True, verbose_name='Citat'),
        ),
    ]
