# Generated by Django 3.2.4 on 2021-06-15 11:46

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_promisepage_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='metasettings',
            name='share_sublabel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='promiseupdate',
            name='content',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Vsebina'),
        ),
    ]
