# Generated by Django 3.2.4 on 2021-06-17 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20210615_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='promisestatus',
            name='order_no',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Vrstni red'),
        ),
    ]
