# Generated by Django 3.2.3 on 2021-06-18 13:59

from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('home', '0025_promisepage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('body', wagtail.core.fields.StreamField([('rich_text', wagtail.core.blocks.StructBlock([('alignment', wagtail.core.blocks.ChoiceBlock(choices=[('start', 'Leva'), ('center', 'Sredinska'), ('end', 'Desna')], label='Poravnava')), ('aligned_content', wagtail.core.blocks.StreamBlock([('text', wagtail.core.blocks.RichTextBlock(label='Obogateno besedilo')), ('table', wagtail.contrib.table_block.blocks.TableBlock(label='Tabela', template='home/blocks/table.html'))], label='Vsebina'))]))], blank=True, null=True, verbose_name='Vsebina')),
            ],
            options={
                'verbose_name': 'Urejanje naročnine',
                'verbose_name_plural': 'Urejanja naročnin',
            },
            bases=('wagtailcore.page',),
        ),
    ]
