# Generated by Django 3.2.4 on 2021-06-18 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_newsletterpage'),
        ('home', '0026_promiselistingpage_no_results'),
    ]

    operations = [
    ]
