# Generated by Django 3.2.3 on 2021-06-21 06:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20210618_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promiseupdate',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datum'),
        ),
    ]
