# Generated by Django 3.2.11 on 2022-04-19 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('home', '0031_contentpage_meta_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infopush',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField(blank=True, null=True, verbose_name='Oznaka')),
                ('title', models.TextField(verbose_name='Naslov (obvezno)')),
                ('text', models.TextField(verbose_name='Opis')),
                ('page_text', models.TextField(verbose_name='Besedilo na gumbu (obvezno)')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page', verbose_name='Povezava do strani (obvezno)')),
            ],
        ),
    ]
