# Generated by Django 3.2.11 on 2022-08-17 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0033_homepage_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='categories_heading',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='latest_button_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='latest_heading',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='latest_link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='search_heading',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='search_link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='search_placeholder',
        ),
        migrations.AddField(
            model_name='homepage',
            name='current_mandate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Trenutno aktualna stran z obljubami'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Naslovna slika'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='more_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Povezava pod opisom (URL)'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='more_link_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Povezava pod opisom (tekst)'),
        ),
    ]
