# Generated by Django 3.2.11 on 2022-08-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20220817_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='social_heading',
        ),
        migrations.AddField(
            model_name='promiseupdate',
            name='conclusion',
            field=models.TextField(blank=True, null=True, verbose_name='Sklep'),
        ),
    ]
