# Generated by Django 3.2.11 on 2022-08-18 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0035_auto_20220817_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promiselistingpage',
            name='about_statuses_text',
        ),
        migrations.RemoveField(
            model_name='promiselistingpage',
            name='category_label',
        ),
        migrations.RemoveField(
            model_name='promiselistingpage',
            name='category_placeholder',
        ),
        migrations.RemoveField(
            model_name='promiselistingpage',
            name='no_results',
        ),
        migrations.RemoveField(
            model_name='promiselistingpage',
            name='search_label',
        ),
        migrations.RemoveField(
            model_name='promiselistingpage',
            name='search_placeholder',
        ),
        migrations.RemoveField(
            model_name='promiselistingpage',
            name='search_title',
        ),
        migrations.RemoveField(
            model_name='promiselistingpage',
            name='status_help_label',
        ),
        migrations.RemoveField(
            model_name='promiselistingpage',
            name='status_help_text',
        ),
        migrations.RemoveField(
            model_name='promisepage',
            name='full_text',
        ),
        migrations.AddField(
            model_name='promisepage',
            name='party_promised',
            field=models.TextField(blank=True, verbose_name='Stranka je obljubila'),
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Ime stranke')),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logotip')),
            ],
        ),
        migrations.AddField(
            model_name='promisepage',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.party', verbose_name='Stranka, ki je dala obljubo'),
        ),
    ]
