# Generated by Django 3.2.11 on 2022-08-18 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_auto_20220818_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={'verbose_name': 'Stranka', 'verbose_name_plural': 'Stranke'},
        ),
    ]
