# Generated by Django 3.2.11 on 2022-08-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_alter_party_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='promiseupdate',
            name='update_author',
            field=models.TextField(blank=True, verbose_name='Avtor/ica posodobitve'),
        ),
    ]
