# Generated by Django 3.2.11 on 2022-08-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_promiseupdate_update_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metasettings',
            name='share_label',
        ),
        migrations.RemoveField(
            model_name='metasettings',
            name='share_sublabel',
        ),
        migrations.AddField(
            model_name='promisepage',
            name='newsletter_box_text',
            field=models.TextField(blank=True, verbose_name='Novičnik tekst v škatli'),
        ),
        migrations.AddField(
            model_name='promisepage',
            name='newsletter_box_title',
            field=models.TextField(blank=True, verbose_name='Novičnik naslov v škatli'),
        ),
    ]
