# Generated by Django 3.2.11 on 2022-08-26 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('home', '0039_auto_20220825_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='mandate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.promiselistingpage', verbose_name='Mandat vlade'),
        ),
        migrations.CreateModel(
            name='GovernmentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('mandate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.promiselistingpage', verbose_name='Vladna stran za vlado:')),
            ],
            options={
                'verbose_name': 'Vladna stran',
                'verbose_name_plural': 'Vladne strani',
            },
            bases=('wagtailcore.page',),
        ),
    ]
