# Generated by Django 3.2.11 on 2022-08-26 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_auto_20220826_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentpage',
            name='mandate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.promiselistingpage', verbose_name='Vladna stran za:'),
        ),
    ]
