# Generated by Django 3.2.11 on 2022-08-26 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0041_alter_governmentpage_mandate'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentpage',
            name='header_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Slika v glavi'),
        ),
    ]
