# Generated by Django 3.2.11 on 2022-08-28 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_auto_20220826_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='partymember',
            name='party',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.party', verbose_name='Stranka'),
            preserve_default=False,
        ),
    ]
