# Generated by Django 3.2.11 on 2022-08-28 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('home', '0044_partymember_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='current_mandate_government_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Trenutno aktualna vladna stran'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='more_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Povezava do prejšnjega mandata'),
        ),
    ]
