# Generated by Django 3.2.11 on 2022-08-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_promisecategory_mandate'),
    ]

    operations = [
        migrations.AddField(
            model_name='promiselistingpage',
            name='government',
            field=models.TextField(blank=True, verbose_name='Sledimo izbranim koalicijskim obljubam'),
        ),
    ]
