# Generated by Django 3.2.11 on 2022-09-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_promiselistingpage_government'),
    ]

    operations = [
        migrations.AddField(
            model_name='promiselistingpage',
            name='government_text',
            field=models.TextField(blank=True, verbose_name='Besedilo do povezave'),
        ),
        migrations.AlterField(
            model_name='promiselistingpage',
            name='government',
            field=models.TextField(blank=True, verbose_name='Besedilo na povezavi (do mandata)'),
        ),
    ]
