# Generated by Django 3.2.11 on 2022-09-01 11:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_auto_20220901_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='partymember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
