# Generated by Django 3.2.11 on 2022-09-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_alter_partymember_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='partymember',
            name='party_comment',
            field=models.TextField(blank=True, verbose_name='Komentar pod stranko'),
        ),
    ]
