# Generated by Django 3.2.11 on 2022-09-11 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_partymember_party_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='metasettings',
            name='meta_image_alt_text',
            field=models.TextField(blank=True, verbose_name='Alt tekst za OG sliko'),
        ),
        migrations.AddField(
            model_name='promisepage',
            name='meta_image_alt_text',
            field=models.TextField(blank=True, verbose_name='Alt tekst za OG sliko'),
        ),
    ]
