# Generated by Django 3.2.17 on 2023-02-15 10:08

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0053_auto_20220911_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metasettings',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta opis'),
        ),
        migrations.AlterField(
            model_name='metasettings',
            name='meta_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='OG slika'),
        ),
        migrations.AlterField(
            model_name='metasettings',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta naslov'),
        ),
        migrations.AlterField(
            model_name='promisepage',
            name='meta_image_alt_text',
            field=models.TextField(blank=True, verbose_name='OG slika alt tekst'),
        ),
        migrations.CreateModel(
            name='OrderablePartyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('government', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='home.governmentpage')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='home.partymember', verbose_name='Član vlade')),
            ],
            options={
                'verbose_name': 'Član vlade',
                'verbose_name_plural': 'Člani vlade',
            },
        ),
    ]
